apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  certSANs:
  - localhost
  - 127.0.0.1
  extraArgs:
    # List of features: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
    # KubeletInUserNamespace=true => Enables support for running kubelet in a user namespace.
    # See how to: https://kubernetes.io/docs/tasks/administer-cluster/kubelet-in-userns/
    feature-gates: KubeletInUserNamespace=true
    runtime-config: ""
    service-node-port-range: {cfg.minNodePort}-{cfg.maxNodePort}
clusterName: {cfg.nodeName}
controlPlaneEndpoint: {cfg.nodeName}:{cfg.bindPort}
controllerManager:
  extraArgs:
    enable-hostpath-provisioner: "true"
    feature-gates: KubeletInUserNamespace=true
kubernetesVersion: {cfg.kubernetesVersion}
networking:
  podSubnet: {cfg.podSubnet}
  serviceSubnet: {cfg.serviceSubnet}
scheduler:
  extraArgs:
    feature-gates: KubeletInUserNamespace=true
---
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- token: abcdef.0123456789abcdef
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: {cfg.nodeIp} 
  bindPort: {cfg.bindPort}
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: {cfg.nodeIp} 
    node-labels: {cfg.nodeLabels}
    provider-id: kind://{cfg.providerId}/{cfg.nodeName}/{cfg.nodeName}-control-plane
---
apiVersion: kubeadm.k8s.io/v1beta3
controlPlane:
  localAPIEndpoint:
    advertiseAddress: {cfg.nodeIp} 
    bindPort: {cfg.bindPort}
discovery:
  bootstrapToken:
    apiServerEndpoint: {cfg.nodeName}-control-plane:{cfg.bindPort}
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: {cfg.nodeIp} 
    node-labels: {cfg.nodeLabels}
    provider-id: kind://{cfg.providerId}/{cfg.nodeName}/{cfg.nodeName}-control-plane
skipPhases:
- preflight
---
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
cgroupRoot: /kubelet
evictionHard:
  imagefs.available: 0%
  nodefs.available: 0%
  nodefs.inodesFree: 0%
failSwapOn: false
featureGates:
  KubeletInUserNamespace: true
imageGCHighThresholdPercent: 100
kind: KubeletConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
conntrack:
  maxPerCore: 0
  tcpCloseWaitTimeout: 0s
  tcpEstablishedTimeout: 0s
featureGates:
  KubeletInUserNamespace: true
iptables:
  minSyncPeriod: 1s
kind: KubeProxyConfiguration
mode: iptables